% Screen
PsychDefaultSetup(2);
[w,wr]=PsychImaging('OpenWindow', 1, [.5 .5 .5]');

% load imageset
img=imageset('/data/cclab/images/Babies', 'Subfolders', {'H', 'bw'; 'L', 'bw-texture'}, 'OnLoad', @deal);
cc=load('/home/cclab/Desktop/ethosal/input/contrast_60images_a.mat');


% parameters needed
mkind = cclabGetMilliKeyIndices();
kbind = 11;
screen_dimensions=[598, 336];
screen_distance=1000;
dummy_mode=1;   % 0 for participant

results=etholog(cc.blocks{1}, img, screen_dimensions, screen_distance, ...
    'ImageChangeType', 'contrast', ...
    'Screen', 1, ...
    'Response', 'MilliKey', ...
    'MilliKeyIndex', mkind, ...
    'KeyboardIndex', kbind, ...
    'Beep', true, ...
    'EyelinkDummyMode', dummy_mode, ...
    'SkipSyncTests', 1);