c2=[1,0,0;1,1,1;1,1,1;1,0,0;1,1,1];
c3=[1,1,1;1,1,1;0,0,1;1,1,1;0,0,1];
c4=[1,1,1;0,1,0;1,1,1;1,1,1;1,1,1];
C={ ...
    'split_screen', [1, 1]; ...
    'mkey', {.9}; ...
    'text', {'This device is called a button box.\nHold it in two hands, with the cord facing away from you.', 'Press any button to continue.'}; ...
    'flip', 0.0; ...
    'wait_button', [1:5]; ...
    'clear_screen', []; ...
    'mkey', {.9, c2'}; ...
    'text', {'Use the two left-most buttons to respond "Left"', 'Press either LEFT button.'}; ...
    'flip', 0.0; ...
    'wait_button', [1,4]; ...
    'clear_screen', []; ...
    'mkey', {.9,c3'}; ...
    'text', {'Use the two right-most buttons to respond "RIGHT"', 'Press either RIGHT button.'}; ...
    'flip', 0.0; ...
    'wait_button', [3,5]; ...
    'clear_screen', []; ...
    'mkey', {.9,c4'}; ...
    'text', {'Use the center button to respond "NONE" - no change.', 'Press the center (NONE) button.'}; ...
    'flip', 0.0; ...
    'wait_button', [2]; ...
    'text', {   'In this experiment, we are interested in our ability to detect changes in different types of pictures.\n'...
                'There are two types of pictures: baby faces....', 'Press any button to continue'}; ...
    'image', {'H/N81'}; ...
    'flip', 0.0; ...
    'wait_button', [1:5]; ...
    'text', {   '... and baby faces that have been digitally altered so they retain the same color and brightness qualities of the original,\n'...
                'but which no longer appear to be a baby....', 'Press any button to continue'}; ...
    'image', {'L/N81'}; ...
    'flip', 0.0; ...
    'wait_button', [1:5]; ...
    'text', {   'The images will be displayed in pairs. Sometimes both images are babies...\n'...
                'Press any button to continue'}; ...
    'image', {{'H/N81', 'H/N81'}}; ...
    'flip', 0.0; ...
    'wait_button', [1:5]; ...
    'text', {   '...sometimes both images will be altered images...\n'...
                'Press any button to continue'}; ...
    'image', {{'L/N81', 'L/N81'}}; ...
    'flip', 0.0; ...
    'wait_button', [1:5]; ...
    'text', {   '...and sometimes there will be one of each...\n'...
                'Press any button to continue'}; ...
    'image', {{'H/N81', 'L/N81'}}; ...
    'flip', 0.0; ...
    'wait_button', [1:5]; ...
    'text', {   '...and the baby may appear on either side...\n'...
                'Press any button to continue'}; ...
    'image', {{'L/N81', 'H/N81'}}; ...
    'flip', 0.0; ...
    'wait_button', [1:5]; ...
    'clear_screen', []; ...
%    'callback', {@(w,r,x, y, z) deal(w,r,x,y,z), 2, [], 'aaa'}; ...
    };
pre=preamble(C,12,resp, imgbw);
pre.play(w);




