local_ethosal;

c2=[1,0,0;1,1,1;1,0,0;1,0,0;1,0,0];
c3=[1,1,1;1,1,1;0,0,1;1,1,1;0,0,1];
c4=[1,1,1;0,0,1;1,1,1;1,1,1;1,1,1];
CC={ ...
'split_screen', [1, 1]; ...
'mkey', {.9}; ...
'text', 'This device is called a button box.\nHold it in two hands, with the cord facing away from you.\nPress any button.'; ...
'flip', 0.0; ...
'wait_button', [0 1]; ...
'clear_screen', []; ...
'mkey', {.9,c4'}; ...
'text', 'Use the center button to respond "NO, I DON''T THINK THE IMAGE FLIPPED"\nPress the center (NONE) button.'; ...
'flip', 0.0; ...
'wait_button', [0]; ...
'clear_screen', []; ...
'mkey', {.9, c2'}; ...
'text', 'Use any other button to respond "YES, I THINK THE IMAGE FLIPPED"\nPress any other button.'; ...
'flip', 0.0; ...
'wait_button', [1]; ...
'slide', {{'H/9','H/10'}, 'Images may be faces... (hit any button)', [0 1]}; ...
'slide', {{'F/9','F/10'}, '...or food... (hit any button)', [0 1]}; ...
'slide', {{'N/9','N/10'}, '...or natural images.', 'Test operator message here on natural image slide.'}; ...
'clear_screen', []; ...
'image', {{'H/9','H/10'}}; ...
'text', 'Images may be faces... (hit any button)'; ...
'flip', 0.0; ...
'wait_button', [0 1]; ...
'clear_screen', []; ...
'image', {{'F/9','F/10'}}; ...
'text', '...food... (hit any button)'; ...
'flip', 0.0; ...
'wait_button', [0 1]; ...
'clear_screen', []; ...
'image', {{'F/9','F/10'}}; ...
'text', 'or natural images... (hit any button)'; ...
'flip', 0.0; ...
'wait_button', [0 1]; ...
'clear_screen', []; ...
'image', {'L/9'}; ...
'text', 'or texturized versions of faces... (hit any button)'; ...
'flip', 0.0; ...
'wait_button', [0 1]; ...
'operator', 'Say something meaningful.'; ...
};


C={ ...
'text', {'Welcome to our experiment!', 'welcome...', }; ...
'slide', {{'H/9'}, 'Images may be child faces...', '111...child faces...'}; ...
'slide', {{'F/9'}, '...or food...', '222...food...'}; ...
'slide', {{'N/9'}, '...or natural images.', '333...or natural images.'}; ...
'slide', {{'H/9','L/19'}, 'In addition, for every image there is a texturized version, which may also be shown...', '555...face and texture...'}; ...
'slide', {{'L/9','H/19'}, 'The texturized image may appear on either side...', '666...texture and image...'}; ...
'slide', {{'L/9','L/19'}, 'There may be two textures...', '777...texture and texture...'}; ...
'slide', {{'H/9','H/19'}, '...or two faces...', '888...or two faces...'}; ...
};
try
    mkind = cclabGetMilliKeyIndices;
    resp=responder(mkind);
    fprintf(1, 'Responder created using index %d\n', mkind);
    [w,wr,mywr]=makeWindow([800,600],0,'center','right');
    % recycle imageset to save time
    if ~exist('img')
        img=imageset(fullfile(ethImgRoot, 'MoreBabies'), '/home/dan/work/cclab/ethosal/paramsCircEdge256_3types');
    end
    pre=preamble(C,18,resp,img);
    pre.play(w);
    clear resp;
    Screen('Close', w);
catch ME
    fprintf(2, '%s\n', getReport(ME));
    sca;
    if exist('resp')
        clear resp;
    end
    if exist('pre')        
        clear pre;
    end
    if exist('img')
        clear img;
    end
end