c2=[1,0,0;1,1,1;1,1,1;1,0,0;1,1,1];
c3=[1,1,1;1,1,1;0,0,1;1,1,1;0,0,1];
c4=[1,1,1;0,1,0;1,1,1;1,1,1;1,1,1];
C={ ...
    'split_screen', [1, 1]; ...
    'mkey', {.9}; ...
    'text', 'This device is called a button box.\nHold it in two hands, with the cord facing away from you.\nPress any button.'; ...
    'flip', 0.0; ...
    'wait_button', [1:5]; ...
    'clear_screen', []; ...
    'mkey', {.9, c2'}; ...
    'text', 'Use the two left-most buttons to respond "Left"\nPress either LEFT button.'; ...
    'flip', 0.0; ...
    'wait_button', [1,4]; ...
    'clear_screen', []; ...
    'mkey', {.9,c3'}; ...
    'text', 'Use the two right-most buttons to respond "RIGHT"\nPress either RIGHT button.'; ...
    'flip', 0.0; ...
    'wait_button', [3,5]; ...
    'clear_screen', []; ...
    'mkey', {.9,c4'}; ...
    'text', 'Use the center button to respond "NONE" - no change.\nPress the center (NONE) button.'; ...
    'flip', 0.0; ...
    'wait_button', [2]; ...
    'clear_screen', []; ...
    };
%pre=preamble(C,12,resp, imgbw);
%pre.play(w);

